In [0]:
!pip install gym
!apt-get install python-opengl -y
!apt install xvfb -y
!pip install pyvirtualdisplay
!pip install piglet
from pyvirtualdisplay import Display
display = Display(visible=0, size=(1400, 900))
display.start()

Reading package lists... Done
Building dependency tree       
Reading state information... Done
Suggested packages:
  libgle3
The following NEW packages will be installed:
  python-opengl
0 upgraded, 1 newly installed, 0 to remove and 25 not upgraded.
Need to get 496 kB of archives.
After this operation, 5,416 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu bionic/universe amd64 python-opengl all 3.1.0+dfsg-1 [496 kB]
Fetched 496 kB in 2s (233 kB/s)
Selecting previously unselected package python-opengl.
(Reading database ... 134448 files and directories currently installed.)
Preparing to unpack .../python-opengl_3.1.0+dfsg-1_all.deb ...
Unpacking python-opengl (3.1.0+dfsg-1) ...
Setting up python-opengl (3.1.0+dfsg-1) ...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  xvfb
0 upgraded, 1 newly installed, 0 to remove and 25 not upgraded.
Need to get 784 kB of 

xdpyinfo was not found, X start can not be checked! Please install xdpyinfo!


<Display cmd_param=['Xvfb', '-br', '-nolisten', 'tcp', '-screen', '0', '1400x900x24', ':1001'] cmd=['Xvfb', '-br', '-nolisten', 'tcp', '-screen', '0', '1400x900x24', ':1001'] oserror=None return_code=None stdout="None" stderr="None" timeout_happened=False>

In [0]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

# This code creates a virtual display to draw game images on. 
# If you are running locally, just ignore it
import os
if type(os.environ.get("DISPLAY")) is not str or len(os.environ.get("DISPLAY"))==0:
    !bash ../xvfb start
    %env DISPLAY=:1

In [0]:
import gym
import cv2
import torch
import torch.nn as n
import torch.optim as op
import torch.nn.functional as f
import gym.spaces
import collections

In [0]:
# https://alexandervandekleut.github.io/gym-wrappers/

In [0]:
# all wrappers are subclass of gym.wrapper or other wrappers
# gym wrapper inherits from gym.env so in super.__init__ in defining wrapper for init to run within in wrapper class 
# we need to pass the env  as it requires it

In [0]:
class Basicwrapper(gym.Wrapper):
  def __init__(self,env):
    super().__init__(env)
    self.env=env
  
  def step(self,action):
    nexts,reward,isdone,info=self.env.step(action)
    #modify 
    return nexts,reward,isdone,info


In [0]:
#  gym.ObservationWrapper: Used to modify the observations returned by the environment. To do this, override the observation method of 
# the environment. This method accepts a single parameter (the observation to be modified) and returns the modified observation.


In [0]:
class observationwrapper(gym.ObservationWrapper):
  def __init__(self,env):
    super().__init__(env)
    self.env=env

  def observation(self,x):
    return x/100.0

In [0]:
#Lets test it out

In [0]:
env1=gym.make("CartPole-v0")

/usr/local/lib/python3.6/dist-packages/gym/logger.py:30: UserWarning: WARN: Box bound precision lowered by casting to float32
  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))


In [0]:
obs=env1.reset()

In [0]:
obs

array([0.04179898, 0.04759913, 0.02559122, 0.00366951])

In [0]:
env2=observationwrapper(gym.make("CartPole-v0"))

/usr/local/lib/python3.6/dist-packages/gym/logger.py:30: UserWarning: WARN: Box bound precision lowered by casting to float32
  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))


In [0]:
obwrap=env2.reset()

In [0]:
obwrap  # During Reset also observation wrapper is being applied

array([0.00017773, 0.00026761, 0.00012652, 0.00027054])

In [0]:
a=env1.step(env1.action_space.sample())

In [0]:
a

(array([ 0.04275096, -0.14788031,  0.02566461,  0.30431565]), 1.0, False, {})

In [0]:
b=env2.step(env2.action_space.sample())

In [0]:
b  # During step and reset() observation wrapper is being applied 

(array([ 0.00018309, -0.0016854 ,  0.00013193,  0.00323702]), 1.0, False, {})